- name: restart apache2
  service:
    name: apache2
    state: restarted
- name: restart httpd
  systemd:
    name: httpd
    state: restarted
- name: restart apache24
  service:
    name: apache24
    state: restarted